### ISSUE TITLE
Upon successful user registration, the main menu is shown, and the user is automatically logged in.

### ISSUE THREAD

**Issue by Darnol** [sopra-fs23-group-29/sopra-fs23-group-29-client#2]

**Comment by mwooll** [comment]
Resolved with commit:
[modified the REST endpoints to match the specification](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-server/commit/0d605dfdb7824ad7339713af8d8f1bb6b7e9f66a) on server
