### ISSUE TITLE
I have to provide my password in order to delete my profile.

### ISSUE THREAD

**Issue by Darnol** [sopra-fs23-group-29/sopra-fs23-group-29-client#23]

**Comment by mwooll** [comment]
Resolved with commits:
[Deleting a User actually works now](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-server/commit/8e87b455da46803146b93d6ce475155c78c3ff66) on server
[Added delete button on the profile edit page. ...](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-client/commit/e7b050ef12d487a61d8d607b7a7c01f377ff2fad) on client
