### ISSUE TITLE
After deleting the profile, the user is redirected to the login page and any token is deleted from the local storage.

### ISSUE THREAD

**Issue by Darnol** [sopra-fs23-group-29/sopra-fs23-group-29-client#25]

**Comment by mwooll** [comment]
Resolved with commit:
[Added delete button on the profile edit page. ...](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-client/commit/e7b050ef12d487a61d8d607b7a7c01f377ff2fad) on client
