### ISSUE TITLE
I place a marker by clicking a flag of the country, the country is highlighted. Then I click a marker. The marker is highlighted.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-client#53]

**Comment by moonaaaw** [comment]
Resolved with commit: [Countries and markers are clickable](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-client/commit/88caf3dcf4f87f5be862ee055cac4d005bb1fdc2)
