### ISSUE TITLE
When my movement does not hit a barrier question, nothing happens and my game piece is moved.

### ISSUE THREAD

**Issue by Nilsils** [sopra-fs23-group-29/sopra-fs23-group-29-client#67]

**Comment by mwooll** [comment]
Resolved with merge
[Merge pull request](https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-client/commit/cef45fa06e81aed9cfdf5a0b3a68e535b57302c0) https://github.com/sopra-fs23-group-29/sopra-fs23-group-29-client/pull/109 on client
